---
- include: os_update.yml
- name: "Reddit App: Install mongodb"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: Import apt key for MongoDB repo
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: EA312927
      state: present

  - name: Install mongodb app repo
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present
      filename: mongodb-org-3.2

  - name: Install mongodb package
    apt:
      update_cache: yes
      name: mongodb-org

  - name: Enable and start mongodb service
    systemd:
      name: mongod.service
      enabled: yes

