---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: parallels
lint:
  name: yamllint
platforms:
  - name: instance
    box: parallels/ubuntu-16.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
